name: Godot Project Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.7.2"
          use-dotnet: false
          include-templates: false
      - name: Validate project
        run: godot --headless --path . --editor --quit
